// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNkVsbD3ejiT2RpYAgmZyK5xzLhOd4iLQ',
    appId: '1:300601293313:web:f1803a6af00875e9a29e00',
    messagingSenderId: '300601293313',
    projectId: 'exit-b140e',
    authDomain: 'exit-b140e.firebaseapp.com',
    storageBucket: 'exit-b140e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdZp233s0NKmQ9oji4i2SS06-ZanhxyRU',
    appId: '1:300601293313:android:cec8f38d9804f936a29e00',
    messagingSenderId: '300601293313',
    projectId: 'exit-b140e',
    storageBucket: 'exit-b140e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_b3mKIoyUa5lyuggDmq9SaaIwSvg5MdE',
    appId: '1:300601293313:ios:8d627d1171c2074aa29e00',
    messagingSenderId: '300601293313',
    projectId: 'exit-b140e',
    storageBucket: 'exit-b140e.appspot.com',
    iosBundleId: 'com.example.exit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_b3mKIoyUa5lyuggDmq9SaaIwSvg5MdE',
    appId: '1:300601293313:ios:bb6a52475a4ca958a29e00',
    messagingSenderId: '300601293313',
    projectId: 'exit-b140e',
    storageBucket: 'exit-b140e.appspot.com',
    iosBundleId: 'com.example.exit.RunnerTests',
  );
}
